add routing logic
bianjieai/tibc-solidity pull request #11
Opened 2021-09-03 11:00 UTC by aofengli

2021-09-06 08:46 UTC, chengwenxi submitted a review, later dismissed

2021-09-07 02:22 UTC, chengwenxi requested changes
pls delete yarn.lock

2021-09-08 03:01 UTC, dgsbl approved these changes

2021-09-08 03:07 UTC, dreamer-zq commented on contracts/core/26-routing/Routing.sol
> +        for (i = 0; i < _rules.length; i++) {
```suggestion
        for (uint256 i = 0; i < _rules.length; i++) {
```

2021-09-08 03:08 UTC, chengwenxi approved these changes

2021-09-08 03:08 UTC, dreamer-zq commented on contracts/core/26-routing/Routing.sol
> +        for (i = 0; i < _rules.length; i++) {
```suggestion
        for (uint256 i = 0; i < _rules.length; i++) {
```

2021-09-08 03:08 UTC, merged